version: '3.4'
services:
  urlspider:
    build:
      .
    environment:
      MYSQL_HOST: 172.29.152.203
      MYSQL_USER: root
      MYSQL_PASSWORD: kasiluo203
      MYSQL_DB: fyspider
    command: ["scrapy","crawl","Url","-a","category=http://www.freebuf.com"]

